#!/bin/bash

base=/sys/class/backlight/intel_backlight
cur=$(<$base/brightness)
max=$(<$base/max_brightness)
min=0
step=100

case $1 in
	up|increase|+) cur=$(($cur + $step)) ;;
	down|decrease|-) cur=$(($cur - $step)) ;;
	check) ;;
	*)  exit 1 ;;
esac

[[ $cur -gt $max ]] && exit 1
[[ $cur -lt $min ]] && exit 1

echo $cur | sudo tee $base/brightness
